language: node_js
node_js:
  - lts/*
script:
  - yarn validate
  - yarn test:coveralls
  - gem install dpl && gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: clean-react-fordevs
  skip_cleanup: true