language: node_js
node_js:
  - lts/*
addons:
  packages:
    - libgconf-2-4
cache:
  directories:
    - node_modules
    - ~/.cache
script:
  - yarn validate
  - yarn test:coveralls
  - yarn test:cypress:ci
before_deploy:
  - yarn global add netlify-cli
  - yarn env-file
  - yarn build
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: master