language: node_js
node_js:
  - lts/*
script:
  - yarn validate
  - yarn test:coveralls
  - gem install faraday-net_http -v 2.1.0
deploy:
  provider: netlify
  site: clean-react-fordevs
  auth: $NETLIFY_KEY
  edge: true