language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - yarn validate
  - yarn test:coveralls
before_deploy:
  - npm install netlify-cli -g
  - yarn build
deploy:
  provider: netlify
  script: netlify deploy --dir=dist --prod
  edge: true
  on:
    branch: master