language: node_js
node_js:
  - lts/*
script:
  - yarn validate
  - yarn test:coveralls
  - echo "API_URL=$API_URL" >> ../.env
build:
  provider: netlify
  site: clean-react-fordevs
  auth: $NETLIFY_KEY
  edge: true