language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - yarn validate
  - yarn test:coveralls
before_deploy:
  - yarn global add netlify-cli
  - yarn env-file
  - yarn build
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: master